# Generated by Django 3.2 on 2023-10-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
    ]
