# Generated by Django 3.2 on 2023-10-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersignup',
            name='postal_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
