# Generated by Django 3.2 on 2023-10-19 05:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_sellersignup_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellersignup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
