# Generated by Django 4.2 on 2024-07-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_rename_sellersignup_seller_sellerproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='country',
        ),
    ]
