# Generated by Django 4.2 on 2024-07-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_remove_seller_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='member_name',
            new_name='seller_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='seller',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
