# Generated by Django 4.2 on 2024-07-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ProductSubCategory',
            new_name='SubCategory',
        ),
    ]
