# Generated by Django 3.2 on 2023-09-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_shippingaddress_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['-open']},
        ),
        migrations.AlterModelOptions(
            name='checkoutreceipt',
            options={'ordering': ['-receipt_sent_date'], 'verbose_name_plural': 'Checkout Receipts'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-open']},
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
