# Generated by Django 3.2 on 2023-09-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230909_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_str_format',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
