# Generated by Django 3.2 on 2023-09-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_price_str_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price_str_format',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
