# Generated by Django 3.2 on 2023-09-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_discount_price_str_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
