# Generated by Django 3.2 on 2023-09-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230910_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_organization',
            field=models.CharField(default='no name', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='no brand', max_length=50),
        ),
    ]
