# Generated by Django 4.2 on 2024-07-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-product'], 'verbose_name_plural': 'Product Images'},
        ),
    ]
