# Generated by Django 3.2 on 2023-09-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230911_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_organization',
            field=models.CharField(default='No name', max_length=50),
        ),
    ]
