# Generated by Django 3.2 on 2023-09-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productsubcategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'ordering': ['category'], 'verbose_name_plural': 'Product Sub-categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller_organization',
            field=models.CharField(max_length=50),
        ),
    ]
