# Generated by Django 3.2 on 2023-09-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutreceipt',
            name='sub_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutreceipt',
            name='tax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutreceipt',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
