# Generated by Django 3.2 on 2023-09-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20230920_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutreceipt',
            name='saving',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
