# Generated by Django 3.2 on 2023-09-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_checkoutreceipt_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
