# Generated by Django 3.2 on 2023-09-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_checkout_total_amount_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
