# Generated by Django 3.2 on 2023-10-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_checkout_total_amount_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutreceipt',
            name='saving',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
