# Generated by Django 3.2 on 2023-10-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_checkoutreceipt_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutreceipt',
            name='saving',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
