# Generated by Django 3.2 on 2023-10-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_checkoutreceipt_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutreceipt',
            name='saving',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
