# Generated by Django 3.2 on 2023-11-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_checkoutreceipt_checkout_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutreceipt',
            name='checkout_summary',
            field=models.FileField(blank=True, null=True, upload_to='checkout_summary'),
        ),
    ]
