# Generated by Django 3.2 on 2023-11-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_checkoutreceipt_checkout_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutreceipt',
            name='checkout_summary',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
