# Generated by Django 3.2 on 2023-11-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_checkoutreceipt_checkout_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutreceipt',
            name='checkout_summary',
            field=models.FileField(blank=True, null=True, upload_to='checkout_summary'),
        ),
    ]
