# Generated by Django 4.2 on 2024-07-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_productreview_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_of_times_solid',
            new_name='num_of_times_sold',
        ),
    ]
