# Generated by Django 4.2 on 2024-07-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price_str_format',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_str_format',
        ),
    ]
