# Generated by Django 4.2 on 2024-07-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_remove_product_discount_price_str_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
