# Generated by Django 4.2 on 2024-07-12 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_product_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
