# Generated by Django 4.2 on 2024-07-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_remove_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller_organization',
            new_name='seller',
        ),
    ]
