# Generated by Django 4.2 on 2024-07-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_rename_seller_organization_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
    ]
