# Generated by Django 4.2 on 2024-07-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_rename_product_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_of_times_sold',
            new_name='quanity_sold',
        ),
    ]
