# Generated by Django 4.2 on 2024-07-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_rename_num_of_times_sold_product_quanity_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quanity_sold',
            new_name='quantity_sold',
        ),
    ]
