# Generated by Django 4.2 on 2024-07-20 20:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0049_alter_shippingaddress_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckoutReceipt',
            new_name='Receipt',
        ),
    ]
