# Generated by Django 4.2 on 2024-07-20 20:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0050_rename_checkoutreceipt_receipt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReview',
            new_name='Review',
        ),
    ]
